# Bitcoin Collections

In this activity, you’ll import the data for the second Bitcoin dataset into a Pandas DataFrame.

Instructions

1. Use the `Path` module with the `read_csv` function to read the `bitcoin_2` csv file into the DataFrame. Be sure to set the `DatetimeIndex`.

2. Using the Pandas `head` function, review the first five rows of the DataFrame to confirm the import.

3. Using the Pandas `tail` function, review the last five rows of the DataFrame.

In [1]:
import pandas as pd
from pathlib import Path

### Import the bitcoin_1 CSV file and create a bitcoin_1 DataFrame

In [2]:
# Read in the CSV file called "bitcoin_1.csv" using the Path module. 
# The CSV file is located in the Resources folder.
# Set the index to the column "Timestamp"
# Set the parse_dates and infer_datetime_format parameters
bitcoin_1 = pd.read_csv(Path('01-Bitcoin_Collections/Resources/bitcoin_1.csv'),
                        index_col = 'Timestamp',
                        parse_dates = True)
bitcoin_1.head()

                     Close
Timestamp
2015-01-01 00:00:00  314.0
2015-01-01 00:01:00  314.0
2015-01-01 00:02:00  314.0
2015-01-01 00:03:00  314.0
2015-01-01 00:04:00  313.9

## Step 1: Use the `Path` module with the `read_csv` function to read the `bitcoin_2` csv file into the DataFrame. Be sure to set the `DatetimeIndex`.

In [3]:
bitcoin_2 = pd.read_csv(Path('01-Bitcoin_Collections/Resources/bitcoin_2.csv'),
                        index_col = 'Timestamp',
                        parse_dates = True)
bitcoin_2.head()

                      Close
Timestamp
2015-01-07 20:24:00  360.00
2015-01-07 20:27:00  276.34
2015-01-07 20:28:00  271.60
2015-01-07 20:29:00  344.67
2015-01-07 20:30:00  305.38

## Step 3: Using the Pandas `tail` function, review the last five rows of the DataFrame.

In [4]:
bitcoin_2.tail()

                      Close
Timestamp
2015-12-31 23:55:00  437.02
2015-12-31 23:56:00  437.07
2015-12-31 23:57:00  436.03
2015-12-31 23:58:00  436.13
2015-12-31 23:59:00  436.12