# Bitcoin Summary Statistics & Plot Bitcoin 2

In the first part of this activity, you’ll generate summary statistics for each dataset and then compare the two datasets.

In the second part of the activity, you’ll plot the visualization for the bitcoin_2 DataFrame.

Instructions:

Bitcoin Summary Statistics:

1. Using the `describe` function, generate summary statistics for the bitcoin_1 DataFrame.

2. Using the `describe` function, generate summary statistics for the bitcoin_2 DataFrame.

3. Compare the summary statistics of the DataFrames. What do the similarities and differences indicate?


Plot Bitcoin_2:

4. Using the Pandas `plot` function, create the visualization for the bitcoin_2 DataFrame. Include the `figsize`, `title`, and `color` (orange) parameters.

In [22]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
%matplotlib inline

### Use the `Path` module and `read_csv` functions to import the CSV files and create the DataFrames

In [3]:
# Read in the CSV file called "bitcoin_1.csv" using the Path module. 
# The CSV file is located in the Resources folder.
# Set the index to the column "Timestamp"
# Set the parse_dates and infer_datetime_format parameters
bitcoin_1 = pd.read_csv(Path('02-Bitcoin_Summary_Statistics/Resources/bitcoin_1.csv'),
                        index_col = 'Timestamp',
                        parse_dates = True)
bitcoin_1.head()

                     Close
Timestamp
2015-01-01 00:00:00  314.0
2015-01-01 00:01:00  314.0
2015-01-01 00:02:00  314.0
2015-01-01 00:03:00  314.0
2015-01-01 00:04:00  313.9

In [4]:
bitcoin_2 = pd.read_csv(Path('02-Bitcoin_Summary_Statistics/Resources/bitcoin_2.csv'),
                        index_col = 'Timestamp',
                        parse_dates = True)
bitcoin_2.head()

                      Close
Timestamp
2015-01-07 20:24:00  360.00
2015-01-07 20:27:00  276.34
2015-01-07 20:28:00  271.60
2015-01-07 20:29:00  344.67
2015-01-07 20:30:00  305.38

### Prepare the DataFrame by addressing missing and duplicate values as well as the data type of each column.

In [5]:
# Use the Pandas isnull function in conjunction with the `sum` function 
# to determine the number of missing values
bitcoin_1.isnull().sum()

Close    0
dtype: int64

In [6]:
# Use the Pandas isnull function in conjunction with the mean function 
# to determine the percentage of missing values
bitcoin_1.isnull().mean()

Close    0.0
dtype: float64

In [7]:
# Use the Pandas duplicated function in conjunction with the sum function
# to determine the number of duplicated values
bitcoin_1.duplicated().sum()

np.int64(347344)

In [8]:
# Use the Pandas isnull function in conjunction with the mean function 
# to determine the percentage of duplicated values
bitcoin_1.duplicated().mean()

np.float64(0.9317842225697677)

In [10]:
# Use the Pandas dtypes function to confirm the data types of each column in the DataFrame
bitcoin_1['Close'].dtypes

dtype('float64')

In [11]:
# Use the Pandas dtypes function to confirm the data types of each column in the DataFrame.
bitcoin_2.dtypes

Close    float64
dtype: object

## Step 1: Using the `describe` function, generate summary statistics for the bitcoin_1 DataFrame.

In [12]:
bitcoin_1.describe()

               Close
count  372773.000000
mean      274.423996
std        61.778634
min       153.100000
25%       233.850000
50%       248.950000
75%       288.820000
max       501.960000

## Step 2: Using the `describe` function, generate summary statistics for the bitcoin_2 DataFrame.

In [14]:
bitcoin_2.describe()

               Close
count  440797.000000
mean      275.956285
std        60.728446
min       109.940000
25%       235.810000
50%       250.540000
75%       289.260000
max       499.260000

## Step 3: Compare the summary statistics of the DataFrames. What do the similarities and differences indicate?

**Question:** Comparing the summary statistics between DataFrames, what do the similarities and differences indicate? 

**Answer:** These datasets are large with several hundred thousand data points. Otherwise, the summary statistics between the two DataFrames are close, but they are not exact.

## Review the plot of the `bitcoin_1` DataFrame.

In [20]:
# Use the default plot to visualize the the `bitcoin_1` DataFrame
# Note the addition of the plot parameters figsize, title, and color.
bitcoin_1.plot(figsize = (10,5), title = 'Bitcoin_1', color = 'blue')

In [23]:
bitcoin_1.plot(figsize=(10, 5), title="Bitcoin_1", color="blue")

## Step 4. Using the Pandas `plot` function, create the visualization for the bitcoin_2 DataFrame. Include the `figsize`, `title`, and `color` (orange) parameters.

In [24]:
# Using the line plot, create a visualiation for the `bitcoin_2` DataFrame
# Be sure to include the parameters figsize, title, and color (use orange)
bitcoin_2.plot(figsize=(10, 5), title="Bitcoin_2", color="orange")

## Review the overlay plot that visualizes the two Bitcoin DataFrames together. Note the addition of the parameters `legend` and `label`.

In [25]:
# Overlay the two DataFrames using the `Close` column as the basis for the plot
# Note the addition of the plot parameters legend and label. 
bitcoin_1['Close'].plot(legend=True, figsize=(15, 7), title="Bitcoin_1 and Bitcoin_2 Overlay Plot", color="blue", label="BTC 1")
bitcoin_2['Close'].plot(legend=True, figsize=(15, 7), color="orange", label="BTC 2")